.model small
.stack
;.386
.data
;VARIABLES TEMPORALES PARA LAS OPERACIONES ARITMETICAS
SIGNOT     db 0
ENTEROST   db 0,0,0,0
DECIMALEST db 0,0,0,0
AUX  dw 0
;VARIABLES PARA LA LEECTURA DE CADENAS
CADENA DW 00
LONGUITUD_CADENA DW 0
BLOQUE_ACTUAL DB 0
ERROR DB 'ERROR','$'
REALLOC DB 10,13,'REALLOC',10,13,'$'
ERROR_ALLOC_CADENA DB 10,13,'OCURRIO UN ERROR RESERVANDO MEMORIA PARA LA CADENA',10,13,'$'
;VARIABLES DEPENDIENTES DE LA PROGRAMACION

;=======>[Mensaje-Cadena]
Mensaje DW 00
LONGUITUD_Mensaje DW 0

;=======>[d0d554dc30c8400ba7a15b6b39e5cfc3-Cadena]
d0d554dc30c8400ba7a15b6b39e5cfc3 DW 00
LONGUITUD_d0d554dc30c8400ba7a15b6b39e5cfc3 DW 0
.code
;INICIA PROCEDIMIENTO PRINCIPAL
begin proc FAR
MOV AX,@data
MOV DS,AX
;================>[CODIGO GENERADO POR EL COMPILADOR]<================
;=================[ASIGNAR VALOR A LA CADENA]=================
MOV BLOQUE_ACTUAL,0D
CALL ALOGAR_CADENA
MOV SI,CADENA
MOV [SI],'H'
INC SI
MOV [SI],'o'
INC SI
MOV [SI],'l'
INC SI
MOV [SI],'a'
INC SI
MOV [SI],' '
INC SI
MOV [SI],'m'
INC SI
MOV [SI],'u'
INC SI
MOV [SI],'n'
INC SI
MOV [SI],'d'
INC SI
MOV [SI],'o'
INC SI
MOV [SI],' '
INC SI
MOV [SI],':'
INC SI
MOV [SI],')'
INC SI
MOV [SI],'$'
MOV DX,CADENA
MOV Mensaje,DX
MOV DX,Mensaje
MOV AH,09H
INT 21H
;=================[ASIGNAR VALOR A LA CADENA]=================
MOV BLOQUE_ACTUAL,3D
CALL ALOGAR_CADENA
MOV SI,CADENA
MOV [SI],'C'
INC SI
MOV [SI],'a'
INC SI
MOV [SI],'d'
INC SI
MOV [SI],'e'
INC SI
MOV [SI],'n'
INC SI
MOV [SI],'a'
INC SI
MOV [SI],' '
INC SI
MOV [SI],'i'
INC SI
MOV [SI],'n'
INC SI
MOV [SI],'c'
INC SI
MOV [SI],'l'
INC SI
MOV [SI],'u'
INC SI
MOV [SI],'i'
INC SI
MOV [SI],'d'
INC SI
MOV [SI],'a'
INC SI
MOV [SI],' '
INC SI
MOV [SI],'d'
INC SI
MOV [SI],'e'
INC SI
MOV [SI],'n'
INC SI
MOV [SI],'t'
INC SI
MOV [SI],'r'
INC SI
MOV [SI],'o'
INC SI
MOV [SI],' '
INC SI
MOV [SI],'d'
INC SI
MOV [SI],'e'
INC SI
MOV [SI],' '
INC SI
MOV [SI],'u'
INC SI
MOV [SI],'n'
INC SI
MOV [SI],'a'
INC SI
MOV [SI],' '
INC SI
MOV [SI],'f'
INC SI
MOV [SI],'u'
INC SI
MOV [SI],'n'
INC SI
MOV [SI],'c'
INC SI
MOV [SI],'i'
INC SI
MOV [SI],'o'
INC SI
MOV [SI],'n'
INC SI
MOV [SI],' '
INC SI
MOV [SI],'s'
INC SI
MOV [SI],'i'
INC SI
MOV [SI],'n'
INC SI
MOV [SI],' '
INC SI
MOV [SI],'a'
INC SI
MOV [SI],'s'
INC SI
MOV [SI],'i'
INC SI
MOV [SI],'g'
INC SI
MOV [SI],'n'
INC SI
MOV [SI],'a'
INC SI
MOV [SI],'r'
INC SI
MOV [SI],'$'
MOV DX,CADENA
MOV d0d554dc30c8400ba7a15b6b39e5cfc3,DX
MOV DX,d0d554dc30c8400ba7a15b6b39e5cfc3
MOV AH,09H
INT 21H
;==============>[FIN CODIGO GENERADO POR EL COMPILADOR]<==============
XOR AX,AX
INT 16H
;================>[LIBERAR TODA LA MEMORIA DE CADENAS]<================
MOV BX,Mensaje
CALL LIBERAR_CADENA
MOV BX,d0d554dc30c8400ba7a15b6b39e5cfc3
CALL LIBERAR_CADENA
MOV AH,4CH
INT 21H
RET

;==============>[PROCEDIMIENTOS INTERNOS GENERADOS POR EL COMPILADOR]<==============

        ;==============>[ALOGAR_CADENA]<==============
        ALOGAR_CADENA PROC NEAR 
    
        ;MOV BLOQUE_ACTUAL,0AH ;INDICA EL BLOQUE EN EL QUE SE ESTA ESCRIBIENDO
    
        ;RESERVAR LA MEOMRIA PARA LEER LA CADENA (MALLOC)
        ;FUNCION AH,48H       
    
        ;PARAMETROS DE ENTRADA:
        ;BX - TAMANIO DE EL BLOQUE (EN PARRAFOS GRUPOS DE 16 BYTES)    
    
        ;PARAMETOS DE SALIDA:  
        ;SI NO HAY ERROR BANDERA DE ACARREO LIMPIA
        ;AX - APUNTA A LA DIRECCION DE INICIO DEL NUEVO BLOQUE RESERVADO
    
        ;SI HAY ERROR ACARREO CON VALOR,
        ;BX - TAMANIO MAXIMO DE MEMORIA DISPONIBLE
        ;AX CODIGO DE ERROR (7 O 8)
              
        MOV AH,48H
        XOR BX,BX
        MOV BL,BLOQUE_ACTUAL ;16*BLOQUE_ACTUAL BYTES DE INICIO
        INT 21H 
        MOV CADENA,AX 
        JC ERROR_ALLOC
        JMP FIN_ALOGAR_CADENA
        ERROR_ALLOC:
    
        MOV AH,09H
        LEA DX,ERROR_ALLOC_CADENA
        INT 21H    
    
        FIN_ALOGAR_CADENA:
        RET
         
    ALOGAR_CADENA ENDP

        ;==============>[ALOGAR_CADENA]<==============
        LIBERAR_CADENA PROC NEAR ;(FREE)
            ;Funcion AH   49h  
            ;PARAMETROS DE ENTRADA: ES:0-DIRECCION BASE CERO DEL BLOQUE PARA LIBERAR
            ;PARAMETROS DE SALIDA: SI EL ACARREO ESTA ACTIVO AX CONTIENE EL CODIGO DE 
            ;ERROR (7,9)
      
            MOV AH,49H 
            MOV ES,BX
            INT 21H
   
            RET
            LIBERAR_CADENA ENDP 
;begin endp
end begin


